//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudireWCF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AudireResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AudireResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudireWCF.AudireResources", typeof(AudireResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AnswerTable.
        /// </summary>
        internal static string AnswerTable {
            get {
                return ResourceManager.GetString("AnswerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @audit_id.
        /// </summary>
        internal static string audit_id {
            get {
                return ResourceManager.GetString("audit_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @audit_type_id.
        /// </summary>
        internal static string audit_type_id {
            get {
                return ResourceManager.GetString("audit_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @auditor_comment.
        /// </summary>
        internal static string auditor_comment {
            get {
                return ResourceManager.GetString("auditor_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @auditType_id.
        /// </summary>
        internal static string auditType_id {
            get {
                return ResourceManager.GetString("auditType_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @deviceID.
        /// </summary>
        internal static string deviceID {
            get {
                return ResourceManager.GetString("deviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @imq_url.
        /// </summary>
        internal static string imq_url {
            get {
                return ResourceManager.GetString("imq_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IsCompleted.
        /// </summary>
        internal static string IsCompleted {
            get {
                return ResourceManager.GetString("IsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @l_err_code.
        /// </summary>
        internal static string l_err_code {
            get {
                return ResourceManager.GetString("l_err_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @l_err_message.
        /// </summary>
        internal static string l_err_message {
            get {
                return ResourceManager.GetString("l_err_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @l_invite_to_list.
        /// </summary>
        internal static string l_invite_to_list {
            get {
                return ResourceManager.GetString("l_invite_to_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @l_location_id.
        /// </summary>
        internal static string l_location_id {
            get {
                return ResourceManager.GetString("l_location_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @module_id.
        /// </summary>
        internal static string module_id {
            get {
                return ResourceManager.GetString("module_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @month.
        /// </summary>
        internal static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_audit_plan_id.
        /// </summary>
        internal static string p_audit_plan_id {
            get {
                return ResourceManager.GetString("p_audit_plan_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_country_id.
        /// </summary>
        internal static string p_country_id {
            get {
                return ResourceManager.GetString("p_country_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_line_id.
        /// </summary>
        internal static string p_line_id {
            get {
                return ResourceManager.GetString("p_line_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_location_id.
        /// </summary>
        internal static string p_location_id {
            get {
                return ResourceManager.GetString("p_location_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_planned_date.
        /// </summary>
        internal static string p_planned_date {
            get {
                return ResourceManager.GetString("p_planned_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_planned_date_end.
        /// </summary>
        internal static string p_planned_date_end {
            get {
                return ResourceManager.GetString("p_planned_date_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_product_id.
        /// </summary>
        internal static string p_product_id {
            get {
                return ResourceManager.GetString("p_product_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_region_id.
        /// </summary>
        internal static string p_region_id {
            get {
                return ResourceManager.GetString("p_region_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_shift_no.
        /// </summary>
        internal static string p_shift_no {
            get {
                return ResourceManager.GetString("p_shift_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @p_user_id.
        /// </summary>
        internal static string p_user_id {
            get {
                return ResourceManager.GetString("p_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @part_name.
        /// </summary>
        internal static string part_name {
            get {
                return ResourceManager.GetString("part_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ReviewTable.
        /// </summary>
        internal static string ReviewTable {
            get {
                return ResourceManager.GetString("ReviewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_checkAuthentication.
        /// </summary>
        internal static string sp_checkAuthentication {
            get {
                return ResourceManager.GetString("sp_checkAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_get_5S_Score.
        /// </summary>
        internal static string sp_get_5S_Score {
            get {
                return ResourceManager.GetString("sp_get_5S_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetAuditPlan.
        /// </summary>
        internal static string sp_GetAuditPlan {
            get {
                return ResourceManager.GetString("sp_GetAuditPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetAuditPlanSubAuditType.
        /// </summary>
        internal static string sp_GetAuditPlanSubAuditType {
            get {
                return ResourceManager.GetString("sp_GetAuditPlanSubAuditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getAuditType.
        /// </summary>
        internal static string sp_getAuditType {
            get {
                return ResourceManager.GetString("sp_getAuditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getCalendarDashboard.
        /// </summary>
        internal static string sp_getCalendarDashboard {
            get {
                return ResourceManager.GetString("sp_getCalendarDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetCountryList.
        /// </summary>
        internal static string sp_GetCountryList {
            get {
                return ResourceManager.GetString("sp_GetCountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getEmployeeList.
        /// </summary>
        internal static string sp_getEmployeeList {
            get {
                return ResourceManager.GetString("sp_getEmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getLandingScreenDetail.
        /// </summary>
        internal static string sp_getLandingScreenDetail {
            get {
                return ResourceManager.GetString("sp_getLandingScreenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetLinesForLocation.
        /// </summary>
        internal static string sp_GetLinesForLocation {
            get {
                return ResourceManager.GetString("sp_GetLinesForLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetLocationList.
        /// </summary>
        internal static string sp_GetLocationList {
            get {
                return ResourceManager.GetString("sp_GetLocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getLoginDetails.
        /// </summary>
        internal static string sp_getLoginDetails {
            get {
                return ResourceManager.GetString("sp_getLoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetMailDetailsForReport.
        /// </summary>
        internal static string sp_GetMailDetailsForReport {
            get {
                return ResourceManager.GetString("sp_GetMailDetailsForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetModuleList.
        /// </summary>
        internal static string sp_GetModuleList {
            get {
                return ResourceManager.GetString("sp_GetModuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getMyAuditDetails.
        /// </summary>
        internal static string sp_getMyAuditDetails {
            get {
                return ResourceManager.GetString("sp_getMyAuditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getOpenTasks.
        /// </summary>
        internal static string sp_getOpenTasks {
            get {
                return ResourceManager.GetString("sp_getOpenTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getPartForProduct.
        /// </summary>
        internal static string sp_getPartForProduct {
            get {
                return ResourceManager.GetString("sp_getPartForProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetProcessList.
        /// </summary>
        internal static string sp_GetProcessList {
            get {
                return ResourceManager.GetString("sp_GetProcessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetProductsForLine.
        /// </summary>
        internal static string sp_GetProductsForLine {
            get {
                return ResourceManager.GetString("sp_GetProductsForLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getProfileScore.
        /// </summary>
        internal static string sp_getProfileScore {
            get {
                return ResourceManager.GetString("sp_getProfileScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getQuestionList.
        /// </summary>
        internal static string sp_getQuestionList {
            get {
                return ResourceManager.GetString("sp_getQuestionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getQuestionListForC.
        /// </summary>
        internal static string sp_getQuestionListForC {
            get {
                return ResourceManager.GetString("sp_getQuestionListForC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetRegionList.
        /// </summary>
        internal static string sp_GetRegionList {
            get {
                return ResourceManager.GetString("sp_GetRegionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_getSectionWiseScore.
        /// </summary>
        internal static string sp_getSectionWiseScore {
            get {
                return ResourceManager.GetString("sp_getSectionWiseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_InsAnswers.
        /// </summary>
        internal static string sp_InsAnswers {
            get {
                return ResourceManager.GetString("sp_InsAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_InsAuditPlan.
        /// </summary>
        internal static string sp_InsAuditPlan {
            get {
                return ResourceManager.GetString("sp_InsAuditPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_InsAuditReview.
        /// </summary>
        internal static string sp_InsAuditReview {
            get {
                return ResourceManager.GetString("sp_InsAuditReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_SaveAuditImages.
        /// </summary>
        internal static string sp_SaveAuditImages {
            get {
                return ResourceManager.GetString("sp_SaveAuditImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_saveProfilePic.
        /// </summary>
        internal static string sp_saveProfilePic {
            get {
                return ResourceManager.GetString("sp_saveProfilePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_SaveReviewImages.
        /// </summary>
        internal static string sp_SaveReviewImages {
            get {
                return ResourceManager.GetString("sp_SaveReviewImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_updatePassword.
        /// </summary>
        internal static string sp_updatePassword {
            get {
                return ResourceManager.GetString("sp_updatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_uploadBulkAuditReview.
        /// </summary>
        internal static string sp_uploadBulkAuditReview {
            get {
                return ResourceManager.GetString("sp_uploadBulkAuditReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_UserLogin.
        /// </summary>
        internal static string sp_UserLogin {
            get {
                return ResourceManager.GetString("sp_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @userID.
        /// </summary>
        internal static string userID {
            get {
                return ResourceManager.GetString("userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @year.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
